module.exports = {
  plugins: [
    "simple-import-sort",
  ],
  env: {
    es2020: true,
    node: true,
  },
  extends: [
    "eslint:recommended",
  ],
  rules: {
    "simple-import-sort/sort": "error",
    "array-bracket-spacing": ["error", "never"],
    "arrow-parens": "error",
    "arrow-spacing": "error",
    "block-spacing": "error",
    "camelcase": "error",
    "comma-dangle": ["error", "always-multiline"],
    "comma-spacing": "error",
    "comma-style": "error",
    "computed-property-spacing": ["error", "never", { enforceForClassMembers: true }],
    "curly": "error",
    "dot-location": ["error", "property"],
    "dot-notation": "error",
    "eol-last": "error",
    "eqeqeq": "error",
    "func-call-spacing": "error",
    "key-spacing": "error",
    "keyword-spacing": "error",
    "no-console": "warn",
    "no-constant-condition": ["error", { checkLoops: false }],
    "no-else-return": "error",
    "no-empty": ["error", { allowEmptyCatch: true }],
    "no-spaced-func": "error",
    "no-useless-call": "error",
    "no-var": "error",
    "object-curly-spacing": ["error", "always"],
    "object-shorthand": "error",
    "prefer-arrow-callback": "error",
    "prefer-const": ["error", { destructuring: "all" }],
    "prefer-rest-params": "error",
    "prefer-spread": "error",
    "prefer-template": "error",
    "quotes": ["error", "double", { allowTemplateLiterals: true }],
    "radix": "error",
    "semi": "error",
    "semi-spacing": "error",
    "space-before-blocks": "error",
    "space-in-parens": "error",
    "switch-colon-spacing": "error",
    "template-curly-spacing": "error",
  },
};
