#!/bin/bash
set -e
set -o pipefail
cd "$( dirname "${BASH_SOURCE[0]}" )"/..

(
  cd csrc
  echo '# <auto-generated> mk/update-list.sh'
  echo 'csrc = files('
  find -name '*.c' -printf '%P\n' | sed "s|.*|'\0'|" | paste -sd,
  echo ')'
) > csrc/meson.build
