package main

import (
	"flag"
	"log"
	"os"
	"strings"
	"text/template"
)

func main() {
	var ta templateArgs
	typeFlag := flag.String("type", "", "list of types, delimited by comma")
	flag.StringVar(&ta.Guard, "guard", "", "#include guard name")
	outputFlag := flag.String("out", "", "output filename")
	flag.Parse()
	var typenames []string
	if *typeFlag != "" {
		typenames = strings.Split(*typeFlag, ",")
	}
	if flag.NArg() != 1 || len(typenames) == 0 || *outputFlag == "" {
		log.Fatal("Usage: enumgen -type=Type0,Type1 -guard=INCLUDE_GUARD -out=output.h path/to/package")
	}
	ta.Init(typenames)
	ta.RecognizeFiles(flag.Arg(0))

	outFile, e := os.Create(*outputFlag)
	if e != nil {
		log.Fatal("cannot open output file", e)
	}
	defer outFile.Close()
	outputTpl.Execute(outFile, ta)
}

type templateArgs struct {
	pkgConsts
	Guard string
}

const outputTemplate = `
{{- /* */ -}}
// <auto-generated> ndn-dpdk/mk/enumgen
#ifndef {{.Guard}}
#define {{.Guard}}
{{range .Enums}}
typedef enum {{.Typename}} {
  {{- range .Definitions}}
  {{.Key}} = {{.Value}},
  {{- end}}
} {{.Typename}};
{{end}}
{{if .Consts}}
enum {
{{- range .Consts}}
  {{.Key}} = {{.Value}},
{{- end}}
};
{{end}}
#endif // {{.Guard}}
`

var outputTpl = template.Must(template.New("").Parse(outputTemplate))
