// <auto-generated> ndn-dpdk/mk/enumgen
#ifndef NDNDPDK_FIB_ENUM_H
#define NDNDPDK_FIB_ENUM_H

enum
{
  FibMaxNameLength = 494,
  FibMaxNexthops = 8,
  FibScratchSize = 96,
};

#endif // NDNDPDK_FIB_ENUM_H
